### ISSUE TITLE
使用该主题失败

### ISSUE THREAD

**Issue by zhaoqize** [yumemor/hexo-theme-primer#8]
将主题clone下来后，修改yml文件为改主题:
```yml
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-primer
```
保存后运行:
```bash
hexo server
```
浏览器请求：http://localhost:4000/

直接控制台报错:
```bash
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: E:\study\blog.zhao\themes\hexo-theme-primer\layout\lay
out.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <%- body %>
    3| <%- partial('_partial/footer') %>
    4| <%- partial('_partial/after-footer') %>

E:\study\blog.zhao\themes\hexo-theme-primer\layout\_partial\head.ejs:21
    19|
    20|         <script>
 >> 21|                 var search_path = "<%= config.search.path %>";
    22|                 if (search_path.length == 0) {
    23|                 search_path = "search.xml";
    24|                 }

Cannot read property 'path' of undefined
    at eval (eval at <anonymous> (E:\study\blog.zhao\node_modules\hexo-renderer-ejs\n
ode_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:932)
    at eval (eval at <anonymous> (E:\study\blog.zhao\node_modules\hexo-renderer-ejs\n
ode_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:1229)
    at E:\study\blog.zhao\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:
255:15
    at _compiledSync (E:\study\blog.zhao\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (E:\study\blog.zhao\node_modules\hexo\lib\theme\view.js:50:21)

    at Object.partial (E:\study\blog.zhao\node_modules\hexo\lib\plugins\helper\partia
l.js:42:17)
    at Object.wrapper (E:\study\blog.zhao\node_modules\hexo\node_modules\lodash\lodas
h.js:4994:19)
    at eval (eval at <anonymous> (E:\study\blog.zhao\node_modules\hexo-renderer-ejs\n
ode_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (E:\study\blog.zhao\node_modules\hexo-renderer-ejs\n
ode_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:222)
    at E:\study\blog.zhao\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:
```

然后切换为hexo自带主题。没有问题。

**Comment by Bakumon** [comment]
默认使用了本地搜索，你改为　google 或者　　[看这里](https://github.com/yumemor/hexo-theme-primer#搜索)
